CREATE TABLE Request (
    RequestNumber INT UNSIGNED NOT NULL AUTO_INCREMENT,
    RequestDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ItemDescription VARCHAR(255) NOT NULL,
    Weight DECIMAL(5,2) NOT NULL,
    PickUpAddress VARCHAR(255) NOT NULL,
    Suburb VARCHAR(50) NOT NULL,
    StateCode VARCHAR(3) NOT NULL,
    CustomerId INT UNSIGNED NOT NULL,
    PRIMARY KEY (RequestNumber),
    FOREIGN KEY (CustomerId) 
        REFERENCES Customer(CustomerId)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (StateCode) REFERENCES State(StateCode)
        ON UPDATE CASCADE 
        ON DELETE RESTRICT
);